swagger: "2.0"
info:
  version: "1.0.0"
  title: "Task Order Microservice"
host: "localhost:8000"
basePath: "/api/"
schemes:
- "http"
paths: 
  /users/login:
    post:
      tags:
      - "user"
      summary: "User login"
      description: ""
      operationId: "userLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login"
        required: true
        type: "string"
      responses:
        "200":
          description: "success login"
          schema:
            type: "string"
          
        "400":
          description: "Invalid username/password"
  /users:
    post:
      tags:
      - "user"
      summary: "Create new user"
      description: ""
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that needs to be added to the user collection"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "success create new user"
    
definitions:
  User:
    type: "object"
    properties:
      _id:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      lastName:
        type: "string"
      gender:
        type: "string"
      address:
        type: "string"
      status:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"